### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by sericaer** [fenix-hub/godot-engine.easy-charts#19]
**Describe the solution you'd like**
Could you raise the priority of developing pie chart?  I need the pie chart.
Thanks a lot !

**Describe an implementation suggestion**

**Additional context**

**Comment by fenix-hub** [comment]
Hi @sericaer ,
I'll give PieChart priority.
Would you be much more interested in PieChart (Control) or PieChart2D (2DNode) ?

**Comment by sericaer** [comment]
I  interest in PieChart (Control) .
Thank you very much.

**Comment by fenix-hub** [comment]
Hi @sericaer ,
Some updates :) 
![lDmOf0usqK](https://user-images.githubusercontent.com/45271396/98279644-7eefc700-1f9a-11eb-9f55-edbaca107dbd.png)

**Comment by sericaer** [comment]
Thanks for the great asset!
And is it update when the data changed dynamic by script?

**Comment by fenix-hub** [comment]
Hi @sericaer ,
You will be able to both display static data from an Array or a CSV File or dynamic data.

**Comment by fenix-hub** [comment]
#21 closes this.
The PieChart needs some testing, especially with real time plotting.
Feel free to open new issues if you find out bugs or just want to request additional features.

**Comment by sericaer** [comment]
Could you upload the scene files which show in gif picture as  the demo?
This will help me to learn how to use it.
Thanks a lot!

**Comment by fenix-hub** [comment]
Hi @sericaer ,
A full documentation will take a lot of time for me.
But I'm planning a new update for the plugin.
After the update will be released I will also post in this same issue a video instead of the scene files :)
This way I'll explain to you almost everything you can do with this plugin (and of course plot the same data you see in the gif, no magic or secret stuff)

**Comment by fenix-hub** [comment]
Hi @sericaer ,
Just discovered that my PC is not that good for making videos.
[Here is a complete guide](https://github.com/fenix-hub/godot-engine.easy-charts/wiki/Static-and-Dynamic-data-plotting-with-PieChart) on how to replicate the same chart you see in the gif, with some little explenations about the functions you will use :)

feel free to ask!
