### ISSUE TITLE
[BUG] Can't plot Line Chart with only values below 1.0

### ISSUE THREAD

**Issue by henricazottes** [fenix-hub/godot-engine.easy-charts#26]
**Describe the bug**
Having a line chart with values exclusively under 1 make it fail to plot.

**To Reproduce**
1. Link a LineChart
2. Add this script to parent node:
``` python
extends Control

func _ready():
	var initial_data: Array = [
		["Time","Alt"],
		["1.0","0.0"],
		["2.0","0.0"],
		["3.0","0.5"]
	]
	$LineChart.plot_from_array(initial_data)
```
3. Run the game
4. See error: Division by zero in operator "/" :

Changing last data with `["3.0", "1.5"]` make it works.

**Expected behavior**
We should have a minimal size plot that can handle values below 1.

**Screenshots**
![image](https://user-images.githubusercontent.com/5214384/101522957-3ad05780-3988-11eb-91b1-7d94de916729.png)

**Desktop (please complete the following information):**
 - OS: Elementary OS
 - Godot Engine Version 3.2.3.stable
- Plugin Version 0.4.2

**Comment by fenix-hub** [comment]
Hi @henricazottes ,
Sorry it took that long.
Next PR will fix this issue. Here's an example:

Code:
```
var initial_data : Array = [
	["Time","Alt","Alt2"],
	[1.0, 1.0, 0.25],
	[2.0, 0.0, 0.05],
	[3.0, 0.5, 5.5],
	]

func _ready():
	$LineChart.plot_from_array(initial_data)
```
Related pic:
![WWN7KFXzNC](https://user-images.githubusercontent.com/45271396/102805094-04003580-43bb-11eb-9a21-f64d7ea0c1ce.png)
