### ISSUE TITLE
[BUG] Charts don't work

### ISSUE THREAD

**Issue by tavurth** [fenix-hub/godot-engine.easy-charts#48]
**Describe the bug**
I wanted to try this library out so I downloaded it, but when trying to load even the examples I get errors because of misnamed files (i.e. `LineChart.tscn` is actually named `line_chart.tscn`)

I see you're going through some refactoring but it would be cool to have the master branch at a useable version.

**To Reproduce**
1. Go to 'github.com'
2. Click on 'clone'
3. Scroll down to 'your project'
4. Try to create a chart

**Expected behavior**
That the master branch holds a stable version

**Desktop (please complete the following information):**
 - OS: Mac
 - Godot Engine Version 3.2
- Plugin Version `master`

**Comment by fenix-hub** [comment]
Hi @tavurth ,
Thanks for this issue. I'll manage to update this plugin as soon as possible to make it usable.
I have been waiting for a contributor to release some changes, but we are both pretty busy, so the plugin has been left back for a while.

**Comment by sairam4123** [comment]
It's been long time, I have been trying to get it working, is there any alternatives to this project?

**Comment by fenix-hub** [comment]
@sairam4123 @tavurth Name mismatches are now solved, you can use LineChart with no issues whatsoever now ;)

**Comment by sairam4123** [comment]
Can you show how to use this project? I have been trying to draw a line chart for my pandemic Simulator.

**Comment by fenix-hub** [comment]
@sairam4123  sure I can help you!! do you mind joining my Discord so we can have a chat there?
or if you prefer you can use the [discussion tabs](https://github.com/fenix-hub/godot-engine.easy-charts/discussions) here.
