### ISSUE TITLE
[BUG] Node Not Found

### ISSUE THREAD

**Issue by RenFinkle** [fenix-hub/godot-engine.easy-charts#52]
**Describe the bug**
When attempting to create a column chart it creates a node with no visuals and spits out multiple node not found errors.

**To Reproduce**
1. Install addon from latest code in repository
2. Enable addon
3. Add ColumnChart node in Control nodes

**Expected behavior**
Create a column chart.

**Screenshots**
![image](https://user-images.githubusercontent.com/11714575/137385338-8c069f3b-8fa4-4983-a327-16f70d824734.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Godot Engine Version: v3.3.3.stable.official.b973f997f
- Plugin Version: Latest at time of writing

**Comment by RenFinkle** [comment]
Update: tried with v1.5.7 on version 3.2 of Godot but I receive this error:
` Attempt to call function 'get_children' in base 'null instance' on a null instance.`

**Comment by sairam4123** [comment]
I'm having the same problem..

**Comment by fenix-hub** [comment]
@sairam4123 @RenFinkle I've started refactoring the plugin, this issue should be ocmpletely solved
