### ISSUE TITLE
[FEATURE] add an examples folder with a working scene

### ISSUE THREAD

**Issue by curioussavage** [fenix-hub/godot-engine.easy-charts#58]
**Describe the solution you'd like**
Thanks for sharing this library. I have spent a lot of time trying to get it to work and so far I can't even get
anything to render on the screen when I place a graph. either trying to render a data frame or using your example files (for the line graph)

It would be super awesome to even just get a simple scene that loads one of your sample files and shows a graph. I'll bet that would be much less work for you too.

**Comment by fenix-hub** [comment]
related to #49

**Comment by fenix-hub** [comment]
@curioussavage thanks for the suggestion. With the new refactoring examples will always be available in the `/examples` folder. Try the ScatterChart one :)
