### ISSUE TITLE
[BUG] Scale of axis does not seem to be linear.

### ISSUE THREAD

**Issue by Lexycon** [fenix-hub/godot-engine.easy-charts#69]
**Describe the bug**
The scale of both axis does not seem to be linear.
It doesn't matter what I set at cp.x_scale_type. Scale is always strange and not linear.

on Y I expect: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
on X I expect: [0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 60]

**Steps to reproduce**
My X axis values are: values = [0, 1, 2, 3, 4, 5, ... 60].
cp.x_scale = 10
LineChart.x = ArrayOperations.multiply_float(values, 0.1)

**Screenshots**
![chart](https://user-images.githubusercontent.com/13588771/215342258-2ab14150-519f-4eea-a017-152a26160d50.png)

**Additional context**
Maybe I am doing sth. wrong, but I can't figure it out tbh.

**Comment by fenix-hub** [comment]
@Lexycon Hi thank for your issue.
This issue should be fixed in release [v29.01.23](https://github.com/fenix-hub/godot-engine.easy-charts/releases/tag/v29.01.23).
Let me know if you still encounter this

**Comment by Lexycon** [comment]
@fenix-hub 

Wow, man, quick response 👍  I tried v29.01.23 and it looks good :)

**Comment by fenix-hub** [comment]
Amazing. Feel free to share your progress on questions on discord :)
