### ISSUE TITLE
Godot 4 compatibility?

### ISSUE THREAD

**Issue by bickford-atherton-morrow** [fenix-hub/godot-engine.easy-charts#72]
With the recent release of Godot 4.0 rc1, I was wondering if any efforts are being made to update this project to be compatible with the changes in GDscript, etc.?

**Comment by fenix-hub** [comment]
Yes, EasyCharts is being ported to 4.x and should be released next week!

**Comment by deevus** [comment]
@fenix-hub From what release is this compatible with Godot 4?

**Comment by fwsmit** [comment]
I cannot find any releases either that support godot 4.x
