### ISSUE TITLE
[FEATURE] x values ​​as sortable text strings

### ISSUE THREAD

**Issue by jospic** [fenix-hub/godot-engine.easy-charts#77]
Hi,
would there be a way to use dates string like "yyyy-mm-dd" as values ​​for the x-axis? 
It would be useful for timing diagrams. 
Thanks in advance.
-j

**Comment by fenix-hub** [comment]
Hi,
Currently you can set custom x-axis and y-axis values using the `x_labels` and `y_labels` directly on a Chart class.
https://github.com/fenix-hub/godot-engine.easy-charts/blob/ecab4394394b1f62c13b917e268953916003aa46/addons/easy_charts/control_charts/chart.gd#LL15C1-L16C37

Would this be enough?

**Comment by jospic** [comment]
Perfect!
Thank you.
-j

**Comment by jospic** [comment]
is there anyway to display these custom labels in tooltips as well?

**Comment by fenix-hub** [comment]
close in favor of #101
