### ISSUE TITLE
[FEATURE] Add option to remove plotted points.

### ISSUE THREAD

**Issue by addmix** [fenix-hub/godot-engine.easy-charts#79]
***Describe the solution you'd like***

Array functions to be exposed on the `Function` class such as `pop_front()` or `remove_at()`
Along with a scrolling graph option that discards "old" values after the domain reaches some size.

***Describe an implementation suggestion***

For every new plotted point, check the oldest point, if the difference between the newest and oldest point has an absolute magnitude greater than some user-defined value, the oldest point is discarded. If that oldest point gets discarded, run the check on the next oldest point until no points are discarded.

***Additional context***

**Comment by fenix-hub** [comment]
If you have any issue with the current implementations, 
please feel free to re-open this issue.

thanks!
