### ISSUE TITLE
[BUG] Realtime plotting not adjusting x bounds of the chart

### ISSUE THREAD

**Issue by Atlinx** [fenix-hub/godot-engine.easy-charts#97]
**Describe the bug**

Plotting values in real-time (adding + removing values such that total # values is the same) does not adjust the x bounds of the chart.

**To Reproduce**
Open and run the line_chart example scene, and press the real-time plotting toggle.

**Expected behavior**
The x bounds of the chart should follow the data.

**Screenshots**
![image](https://github.com/fenix-hub/godot-engine.easy-charts/assets/25368491/4a242f58-da3d-4d0c-b7f6-7322710c1ce8)

**Desktop (please complete the following information):**
 - OS: Windows
 - Godot Engine Version: v4.2.1.stable.official [b09f793f5]
- Plugin Version: Main branch (5c8f22c19d8ff8e0e6c94af0e7703da7e9fdc829)

**Additional context**
This might be due to the main branch being a development/incomplete branch.

**Comment by calumk** [comment]
It seems to work intermittantly for me - it kind of scales from 0-2, to 10-20, and then rolls - i guess its rounding somewhere.

https://github.com/fenix-hub/godot-engine.easy-charts/assets/1183991/169b1067-d759-4979-95c0-656d06aeab69

**Comment by fenix-hub** [comment]
Thank you for your feedbacks.
I'll be back on working on this project this weekend.
sorry for the inconvenience

**Comment by zedzag** [comment]
has anyone found a workaround for this?

**Comment by calumk** [comment]
For my use case i switched to : https://github.com/LD2Studio/godot4-graph2d

**Comment by fenix-hub** [comment]
https://github.com/fenix-hub/godot-engine.easy-charts/assets/45271396/12b51d1f-860d-4028-8dc0-801090b4a181

Hi, 
the new release will fix this  bug.
Thank you for your patience

**Comment by calumk** [comment]
Great thanks :)

**Comment by CsloudX** [comment]
this bug was fixed in 2024, but why [V28.08.25](https://github.com/fenix-hub/godot-engine.easy-charts/releases/tag/v28.08.25) has this bug?
