### ISSUE TITLE
[FEATURE] would be awesome to actually have examples

### ISSUE THREAD

**Issue by dinopanagos** [fenix-hub/godot-engine.easy-charts#98]
Example page is all over the place, took a few hours tried to get it to work but way too difficult for a plugin. Should be able to instantiate one of the chart nodes and pass in properties and values in code, just way to messy.
Not worth the time, gave it a chance, thnx mate.
if the examples pages changes will give it another go

**Comment by fenix-hub** [comment]
Hi, there are already some examples in the project.
You can find them in the [examples](https://github.com/fenix-hub/godot-engine.easy-charts/tree/main/addons/easy_charts/examples) folder.

**Comment by dinopanagos** [comment]
Werent clear enough, plugin should be out of the box plug in play w clear example. This too all over the place. Made a custom solution in about 2 hours. Will turn it into a plugin. Thanks for the foundation though. 👍

**Comment by fenix-hub** [comment]
You are welcome

**Comment by chaojian-zhang** [comment]
> Werent clear enough, plugin should be out of the box plug in play w clear example. This too all over the place. Made a custom solution in about 2 hours. Will turn it into a plugin. Thanks for the foundation though. 👍

@dinopanagos Any information on your "custom solution in about 2 hours" (A github link maybe)? Would be helpful if you can shed some light on what's the approach for a custom implementation as well. Thanks!

**Comment by dinopanagos** [comment]
@chaojian-zhang sorry my repos are private since they are for prod game dev, but yeah i was able to crank out my own charting global script that takes in new params to make it way more simple, also made it so you can choose to add a number/date to the points. Did it all with drawing lines with the ability to draw mini dots/circles on connecting lines on the plot. Just 100x easier then having to add all these files and jargon, its just one simple singleton you can reference.

Note: this is just for a line graph, didnt need any other graphs as of yet.
